include:
  - path: ./cuos-release/cuos-iac-webui/docker-compose.yml
  - path: ./cuos-release/cuos-iac-fleet-agent/docker-compose.yml
  - path: ./cuos-release/cuos-dev-container/docker-compose.yml

services:
  welcome:
    image: docker/welcome-to-docker
    ports:
      - "80:80"
