services:
  iac-manager-webui:
    image: "ghcr.io/cuos-dev/cuos-iac-webui:latest"
    volumes:
      - /var/run/cuos.sock:/var/run/cuos.sock
      - /system.json:/system.json:ro
    ports:
      - "8030:3000"
    restart: always
#    profiles:
#      - dev

